### ISSUE TITLE
Warn users when they are at risk of overwriting a module

### ISSUE THREAD

**Issue by ettorerizza** [CJWorkbench/cjworkbench#102]
Hello, I forked one of your modules (regexextractor) and reimported it mindlessly into my Workbench session, forgetting to change its name in the json. Result: it looks like my version of the module has replaced the original one, and it seems a bit difficult to restore it. 

![screenshot-app workbenchdata com-2019 02 11-14-46-27](https://user-images.githubusercontent.com/6286410/52567201-00d5af00-2e0c-11e9-8162-c3463af56370.png)

Perhaps users should be informed when they are about to overwrite an existing module.

**Comment by jstray** [comment]
Hi! You should be able force reimporting by running the following command:

`bin/dev python manage.py import-modules regexextractor`

**Comment by adamhooper** [comment]
To avoid confusion, I'm tempted to infer module IDs from Git project URLs:

* `https://github.com/CJWorkbench/regexextractor.git` => module ID is `regexextractor` (GitHub+CJWorkbench are implicit)
* `https://github.com/ettorerizza/regexextractor.git` => module ID is `ettorerizza/regexextractor` (GitHub is implicit)
* `https://gitlab.com/ettorerizza/regexextractor.git` => module ID is `https://gitlab.com/ettorerizza/regexextractor.git`

Beware non-canonical URLs. `https://gitlab.com/ettorerizza/regexextractor.git` and `https://gitlab.com/ettorerizza/regexextractor` may _look_ like the same repo, but that isn't the case for every git server. Also, `CJWorkbench/regexextractor` and `cjworkbench/regexextrator` happen to be the same; but we can't know whether other git servers case-fold. The solution:

1. The first time a user imports a URL, canonicalize it. (Downcase; nix "http:" and "https:"; nix ".git"; nix "//github.com/[user]") Store the canonical and original versions of the URL.
2. The subsequent time a user imports a URL, canonicalize again. If the canonical URL was already stored, and the user-provided URL is different from the original, prompt the user to enter the original URL instead.

**Comment by adamhooper** [comment]
Only administrators can import modules now. So this issue may come up in dev mode, but it isn't likely on production.

In the future, we're going to enforce module IDs as I mentioned in my previous comment -- with ID being derived from git-repo URL.
