### ISSUE TITLE
Is there some tidy - wide to long - module?

### ISSUE THREAD

**Issue by aborruso** [CJWorkbench/cjworkbench#119]
Hi,
often we have this kind of table (the image below), that it's necessary to "tidy" in

|Anno|Key|Value|
|---|---|---|
|1966|Nazione 1| Italia|
|1966|Nazione 2| Algeria|
|...|...| ...|

It would be great to have a tidy module - both wide to long and long to wide - in workbenchdata.

Thank you

![image](https://user-images.githubusercontent.com/30607/57176699-5e055d80-6e5b-11e9-960e-d961e2e83cde.png)

**Comment by jstray** [comment]
This exists! It's called Reshape
http://help.workbenchdata.com/modules/clean/reshape

**Comment by aborruso** [comment]
Thank you very much
