### ISSUE TITLE
Multiply by number other than 1 fails

### ISSUE THREAD

**Issue by milafrerichs** [CJWorkbench/cjworkbench#122]
You can take a look at this workflow:
https://app.workbenchdata.com/workflows/17339/

In the tab1 I try to multiply a result by a value (1000) but it silently fails and the server response in the console is the following:

```
Message from server:  – "ValueError: Value 10000 is not a float" – Error: Server responded with error
Error: Server responded with error
construct
o — construct.js:30
t — wrapNativeSuper.js:26
t — WorkflowWebsocket.js:13
(anonyme Funktion) — WorkflowWebsocket.js:65
```
not much help I assume. 
I tried to search the repo for the error but could not find anything. I tried to search for multiply or calculate and could not find something either. 

Hope this helps.

**Comment by jstray** [comment]
Hi Mila. That workflow is not public, can you share it?
Also, what step are you using to multiply? Calculate? Formula?

**Comment by milafrerichs** [comment]
@jstray it is now public. 
I'm using Calculate.

**Comment by jstray** [comment]
Thanks Mila, we have fixed the bug and it should be deployed in the next day or so. Meanwhile, you can get around this by using a floating point number, like 10.0001 instead of 10.

**Comment by milafrerichs** [comment]
@jstray thank you for the quick fix. I tried that but the input field only accepts integers. it will always convert floats to ints :)
