### ISSUE TITLE
Module docs referenced "Import from GitHub" which doesn't seem to exist

### ISSUE THREAD

**Issue by onyxfish** [CJWorkbench/cjworkbench#127]
Maybe I'm blind or maybe this feature was dropped, but I can't find it anywhere. Here's [the relevant section](https://github.com/CJWorkbench/cjworkbench/wiki/Creating-A-Module#importing-a-module) of the docs.

**Comment by jstray** [comment]
Docs updated to clarify that only admin users get this.
