### ISSUE TITLE
Logout destroys language setting

### ISSUE THREAD

**Issue by adamhooper** [CJWorkbench/cjworkbench#155]
Steps to reproduce:

1. Log in
2. Choose Greek language
3. Log out

Expected results: things are still Greek
Actual results: back to English!

This is because when the user logs out, we destroy the session.

One solution is to use a separate cookie for language. This would make our solution to #149 seem to fit in, too. On #149 I was suggested two different pieces of middleware running at two different times. Now I'm also suggesting two different cookies -- one per middleware.

**Comment by giorgio93p** [comment]
It is a bit counter-intuitive, indeed.

Question: What language should we show after the following scenario?

- Set to Greek
- Login
- Set to English
- Logout

**Comment by adamhooper** [comment]
Let's go with:

After step 2: the user's language (because the user stored it in the database during a previous session)

After step 4: English (because the previous page was English -- had step 3 never happened, it would be the user's language from the database)
