### ISSUE TITLE
Placeholder of custom module parameters

### ISSUE THREAD

**Issue by giorgio93p** [CJWorkbench/cjworkbench#159]
In `cjwstate/modules/module_spec_schema.yaml`, module parameters of type custom are [defined](https://github.com/CJWorkbench/cjworkbench/blob/1235ea4cf75937d34647c5b783fad239c29d1fc7/cjwstate/modules/module_spec_schema.yaml#L342) as supporting a placeholder property. However, in `cjwstate/models/param_specs.py`, `ParamSpecCustom` [does not inherit](https://github.com/CJWorkbench/cjworkbench/blob/1235ea4cf75937d34647c5b783fad239c29d1fc7/cjwstate/models/param_spec.py#L272) from `_HasPlaceholder`.

**Comment by adamhooper** [comment]
Good eye! I'll remove it from the spec.

If a module import breaks because of this change, we can always revert and add `_HasPlaceholder`.
