### ISSUE TITLE
Warning Dialog while deleting Tabs 

### ISSUE THREAD

**Issue by arky** [CJWorkbench/cjworkbench#215]
Please kindly provide a warning when a user deletes a tab with something 'This action will remove the workflow tab, this action is not reversible'. 

While 'Undo/Redo' option could restore the tabs, it would be good to warn the users about such board sweeping change actions.

**Comment by adamhooper** [comment]
@arky Is the action reversible? What happens after you press Undo?

**Comment by arky** [comment]
@adamhooper There are no errors. I wrongly assumed deleting tabs is a potentially destructive process.
