### ISSUE TITLE
Support accessing private APIs

### ISSUE THREAD

**Issue by arky** [CJWorkbench/cjworkbench#216]
Please kindly provide support for API calls with API Key authorization. This would enable us to query APIs which are not public. 

The use-case for this is Open Apparel Project that provides information about supply chains. We are trying create datasets by querying using provided API keys. 

https://openapparel.org/

https://openapparel.org/api/docs/

**Comment by adamhooper** [comment]
Workbench does support API keys. You need to author a new Step module to create the API-key prompt. The Step module could also transform API responses into tabular data.

To contact us for help, please email hello@workbenchdata.com.
