### ISSUE TITLE
docker frontend: No module named httpprocessproxy

### ISSUE THREAD

**Issue by enodr** [CJWorkbench/cjworkbench#221]
Hi,

When trying to run the docker-compose I have the following error. I cannot find any reference to "httpprocessproxy" python module beside in docker-compose.yml which uses this command:
cjwkernel/setup-sandboxes.sh only-readonly && pipenv run python -m httpprocessproxy 0.0.0.0:8000 0.0.0.0:8080 --exclude ...

```
# docker-compose up frontend
cjworkbench_minio_1 is up-to-date
cjworkbench_rabbitmq_1 is up-to-date
cjworkbench_database_1 is up-to-date
Starting cjworkbench_frontend_1 ... done
Attaching to cjworkbench_frontend_1
frontend_1      | /root/.local/share/virtualenvs/app-4PlAip0Q/bin/python: No module named httpprocessproxy
cjworkbench_frontend_1 exited with code 1
```

Edit: host platform is Windows. I guess this is unsupported, works fine under Linux.

**Comment by adamhooper** [comment]
Hi @enodr,

Thanks for connecting! We don't actually support running `docker-compose` directly. Could you please paste the entire output of `bin/dev start`?

**Comment by adamhooper** [comment]
Closing after receiving no response
