### ISSUE TITLE
`bin/dev start` error prevents server from starting

### ISSUE THREAD

**Issue by Glench** [CJWorkbench/cjworkbench#277]
When running `bin/dev start` it goes through a bunch of stuff and then fails and stops running on this line.
```
Pulling intercom-sink (gcr.io/workbenchdata-ci/cjw-intercom-sink:38d0dfbb2dc90a1c978b4bb80ea5b145cdfe3591)...
ERROR: Head "https://gcr.io/v2/workbenchdata-ci/cjw-intercom-sink/manifests/38d0dfbb2dc90a1c978b4bb80ea5b145cdfe3591": denied: Project workbenchdata-ci has been deleted.
```

Any ideas?

**Comment by adamhooper** [comment]
Thank you for the bug report!

As part of our project shutdown, we shut down the `workbenchdata-ci` project. But hell, the only thing you need it for is Intercom messaging ... and we shut down our Intercom project, too! So I'll go ahead and delete all that unused tracking code.

**Comment by Glench** [comment]
Figured as much!

Thanks for open sourcing this project. I talked with Pierre several times and am happy it didn't just completely go off the internet. Really a fantastic example of beautiful, UX-driven end-user programming. Shame it wasn't sustainable.

**Comment by adamhooper** [comment]
@Glench Give it a shot! I've deleted everything related to Intercom :). (There's still a "Sign up for newsletter?" prompt, but it won't actually sign you up to anything.)

**Comment by Glench** [comment]
worked this time, thanks!
