### ISSUE TITLE
Uploader and paste functions not working

### ISSUE THREAD

**Issue by Glench** [CJWorkbench/cjworkbench#278]
After properly running the install instructions [here](https://github.com/CJWorkbench/cjworkbench/wiki/Setting-up-a-development-environment) I was able to successfully create a new user and log in.

When I try to make a new workflow with either the CSV file uploader or the paste data function (clicking the little arrow), nothing happens. No JS errors, no python errors. The file uploading server debugging info shows the file uploader was working, but the main table on the page never actually changes to reflect the data — it just stays blank.

![Screen Shot 2022-02-02 at 10 15 54 AM](https://user-images.githubusercontent.com/451461/152182023-2e405756-35ba-43b5-92e0-49b3d3ae943b.png)

There is also a continual loading icon at the bottom of the screen that never goes away. Not sure if this is related.

**Comment by adamhooper** [comment]
This probably means the "renderer" isn't running. (We use "Paste Data" as our most-basic test. I tested "Paste Data" works for me on a brand-new instance.)

What's your operating system? What version of Docker are you using?

**Comment by Glench** [comment]
I just made a clean repo and it worked, so all good for now! Thank you so much for your help.
