### ISSUE TITLE
webpack-stats.json issue

### ISSUE THREAD

**Issue by bkamapantula** [CJWorkbench/cjworkbench#6]
hi

I'm setting up the dev environment and followed the steps [from here](https://github.com/CJWorkbench/cjworkbench/wiki/Setting-up-a-development-environment). 

`python manage runserver` works fine although upon hitting the 127.0.0.1:8000, it throws a 

`error reading /cjworkbench/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`

I guess one of the steps needs webpack setup and I haven't done that. Can you please let me know how can I fix this?

**Comment by milafrerichs** [comment]
In development mode you need to run `./watchjs` (or equivalent if you do not run unix) to generate the js files

**Comment by bkamapantula** [comment]
thanks @milafrerichs, I missed that step in the `dev` mode. works fine after `./watchjs`
