### ISSUE TITLE
Resizing plot/chart area or hiding data for viz step

### ISSUE THREAD

**Issue by abedkhooli** [CJWorkbench/cjworkbench#94]
Is it possible to either increase the height of the chart area or hide the data grid underneath? Something like the resizing of column widths but horizontal.

**Comment by jstray** [comment]
No, but you can export the chart in a variety of formats, or embed it.

**Comment by abedkhooli** [comment]
I think plots can benefit from both resizing (up to hiding data beneath chart area) and mouse over functionality (data series, x and y values).

**Comment by adamhooper** [comment]
@abedkhooli The "Embed" page might suit your needs exactly, if we're lucky. Try this:

1. Click the `</>` icon on the chart
2. Copy the URL in the `<iframe src="...URL..."...></iframe>` part of the embed code
3. Navigate to that URL
4. Resize your browser window

Does that match your expectations?

**Comment by abedkhooli** [comment]
Not really. The idea is to be able to view your work easily inside WB and try out options and filters before embedding - after all, this is the spirit of WB.

**Comment by adamhooper** [comment]
Two years late to the party...:

Workbench now hides the data when viewing a chart step. So you can see the chart full-size when you select the "Chart" step, and you can see the data full-size when you select the previous step.
