### ISSUE TITLE
No export button on charts?

### ISSUE THREAD

**Issue by jonkeegan** [CJWorkbench/cjworkbench#97]
I have a column chart that is public, but in the editor, I see no export button in the upper right hand corner. There is only the embed button. Am I missing a setting somewhere?

https://app.workbenchdata.com/workflows/7700

Thanks!

Mac Mojave 10.14.1 (18B75)
This is in both Safari Version 12.0.1 (14606.2.104.1.1) and 
Chrome Version 70.0.3538.102 (Official Build) (64-bit)

![screenshot 2018-11-20 00 45 43](https://user-images.githubusercontent.com/429123/48753867-a0e0c980-ec5d-11e8-8bbc-8ca951e50e7e.png)

**Comment by jstray** [comment]
Hi Jon! We discovered this bug yesterday and we are working on it -- thanks for the report.

**Comment by adamhooper** [comment]
Fixed ages ago.
